### ISSUE TITLE
TODO - update to Kops 1.10.1

### ISSUE THREAD

**Issue by pahud** [nwcdlabs/kops-cn#41]
https://github.com/kubernetes/kops/releases/tag/1.10.1

- [ ] mirror the assets and FileRepository
- [ ] update README(English)
- [ ] update README(Chinese)
